qian/urls.py
from django.urls import path
from . import views
app_name = 'qian'

urlpatterns=[
path('',views.index,name='index'),

]

qiandao_d/urls.py
# -*- coding:utf-8 -*-
#from Ding import *
import schedule
import time
import threading
from qian.models import data,log_a
from django.contrib import admin
from django.urls import path
from django.urls import include, path
import requests,json,uuid
import datetime
#log.objects.all().delete()


class qian:
    def __init__(self):
        self.data=data.objects.all()
    def qian(self):
       try:
        for i in self.data:
           try:
            print(i.name)
            if i.fk=='GET':            
              if i.cookie=='null':
               print('没cookie')
               a=requests.get(i.url,data=i.data,headers=eval(i.header))              
              else:
               print('有cookie')
               a=requests.get(i.url,data=i.data,cookies=eval(i.cookie),headers=eval(i.header))
              
              try:
                   print(json.loads(a.text))
                   b=log_a.objects.create(user=uuid.uuid1(),name=i.name,username=i.user,data=str(a.json()),time= datetime.datetime.now())
               
              except:
                   print(a.text)
                   b=log_a.objects.create(user=uuid.uuid1(),name=i.name,username=i.user,data=str(a.text),time= datetime.datetime.now())
             
            elif i.fk=='POST':
              if i.cookie=='null':
               print('没cookie')
               a=requests.post(i.url,data=i.data,headers=eval(i.header))              
              else:
               print('有cookie')
               a=requests.post(i.url,data=i.data,cookies=eval(i.cookie),headers=eval(i.header))
             
              try:
                   print(json.loads(a.text))
                   b=log_a.objects.create(user=uuid.uuid1(),name=i.name,username=i.user,data=str(a.json()),time= datetime.datetime.now())
               
              except:
                   print(a.text)
                   b=log_a.objects.create(user=uuid.uuid1(),name=i.name,username=i.user,data=str(a.text),time= datetime.datetime.now())
             
           except:
              print('错误')            
                #未完              
       except:
         print('错误')    
def job():
    print("I'm working...")
    a=qian()
    a.qian()

schedule.every(20).minutes.do(job)
#schedule.every().hour.do(job)
#schedule.every().day.at("00:00").do(job)
#schedule.every().monday.do(job)
#schedule.every().wednesday.at("13:15").do(job)

def xxx():
    while True:
        schedule.run_pending()
        time.sleep(1)
      
t =threading.Thread(target=xxx)
t.start()



urlpatterns = [
    path('admin/', admin.site.urls),
     path('qian/', include('qian.urls')),
]

qian/models.py
from django.db import models

# Create your models here.



class user(models.Model):
    username = models.CharField(max_length=200,primary_key=True)
    pwd = models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    time=models.DateTimeField('date published')
    rmb = models.IntegerField(default=0) 
    yingyong = models.IntegerField(default=2) 
    class Meta:
        #末尾不加s
        verbose_name_plural='用户'
    def __str__(self):
        return self.username
  
class data(models.Model):
    user = models.ForeignKey(user, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)#miui
    fk = models.CharField(max_length=200)#get or post
    url = models.CharField(max_length=500)#url
    cookie = models.TextField()
    header = models.TextField()
    data=models.TextField(blank=True)
    class Meta:
        #末尾不加s
        verbose_name_plural='签到任务'

    
    def __str__(self):
        return self.name
    
class log_a(models.Model):
    user = models.CharField(max_length=200,primary_key=True)
    username=models.CharField(max_length=200)
    data = models.TextField()
    name=models.CharField(max_length=200)
    time=models.DateTimeField('date published')
    class Meta:
        #末尾不加s
        verbose_name_plural='日志'
    
    def __str__(self):
        return self.username

qian/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import data,user
# Create your views here.
from . import HttpPars
import json
#print(HttpPars.HttpPars(a).Pars())



def index(request):
     #return HttpResponse('666')
     if request.method=='GET':     
           return render(request,'qian/index.html')       
     if request.method=='POST':
           name=request.POST['name']      
           http=request.POST['http']
           open('xx.txt','w').write(http)
           print(http)
           try:
             dict=HttpPars.HttpPars(str(http)).Pars()
          # print(dict)
             x=json.dumps(dict, ensure_ascii=False,sort_keys=True, indent=4, separators=(',', ': '))       
             print(x)
             b=data.objects.create(user=user.objects.all()[0],name=name,fk=dict['fk'],url=dict['url'],cookie='null',header=dict['header'],data=dict['data'])
           
             return HttpResponse('<h1>:)  添加成功<br></h1>'+x)
           except:
             return HttpResponse('<h1>:)  添加失败<br></h1>')
           
     
 

qian/templates/qian/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"> 
    <title>创建签到任务</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css"> 
    <script src="//cdn.bootcss.com/codemirror/5.2.0/codemirror.min.js"></script>
    <link rel="shortcut icon" href="//static.runoob.com/images/favicon.ico" mce_href="//static.runoob.com/images/favicon.ico" type="image/x-icon" >
	<link rel="stylesheet" href="//cdn.bootcss.com/codemirror/5.2.0/codemirror.min.css">
	<script src="//cdn.bootcss.com/codemirror/5.2.0/mode/htmlmixed/htmlmixed.min.js"></script>
	<script src="//cdn.bootcss.com/codemirror/5.2.0/mode/css/css.min.js"></script>
	<script src="//cdn.bootcss.com/codemirror/5.2.0/mode/javascript/javascript.min.js"></script>
	<script src="//cdn.bootcss.com/codemirror/5.2.0/mode/xml/xml.min.js"></script>
	<script src="//cdn.bootcss.com/codemirror/5.2.0/addon/edit/closetag.min.js"></script>
	<script src="//cdn.bootcss.com/codemirror/5.2.0/addon/edit/closebrackets.min.js"></script>
	<!--[if lt IE 9]>
	<script src="//cdn.bootcss.com/html5shiv/r29/html5.min.js"></script>
	<![endif]-->
</head>
<body>
<center><h1>创建签到任务</h1></center>
<style>
table {
font-size:20px;
}

body{min-height:20px;padding-top:20px;background: #f6f6f6;}.container{width:98%;padding-right:10px;padding-left:15px;margin-right:auto;margin-left:auto}.CodeMirror{min-height:250px;;font-family: Menlo,Monaco,Consolas,"Andale Mono","lucida console","Courier New",monospace;}#textareaCode{min-height:200px}#iframeResult{display: block;overflow: hidden;border:0!important;min-width:100px;width:100%;min-height:20px;background-color:#fff}@media screen and (max-width:768px){#textareaCode{height:200px}.CodeMirror{height:300px;font-family: Menlo,Monaco,Consolas,"Andale Mono","lucida console","Courier New",monospace;}#iframeResult{height:300px}.form-inline{padding:6px 0 2px 0}}.logo h1{background-image:url(/images/logo-domain-white.png);background-repeat:no-repeat;text-indent:-9999px;width:160px;height:39px;margin-top:10px;display:block}
</style>
				<div class="panel-body">
				 <form action="{% url 'qian:index' %}" method="post">
{% csrf_token %}
		 <input name="name" type="text" class="form-control" id="name" placeholder="请输入任务名称">
<br>
<table>
			<textarea  type="text" placeholder="请输入http报文" class="form-control"  id="textareaCode" name="http">
</textarea>
</table>
<br>
<button class="btn btn-primary btn-lg btn-block">提交签到任务</button>
</form>
	</div>
</div>
</div></body>
</html>

qian/templates/qian/xxx.html
<!--
<h1>
<form action="{% url 'xxx01:index' %}" method="post">
{% csrf_token %}
用户名:
<input name="username"  />
<br>
邮箱:
<input name="email" />
<br/>

密码:
<input name="pwd" />


<input type="submit" value="提交" />





</form>
</h1>
-->



<html ng-app="ionicApp">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
        <title>提交注册信息</title>
        <link href="https://cdn.bootcss.com/ionic/1.3.2/css/ionic.css" rel="stylesheet">
        <script src="https://cdn.bootcss.com/ionic/1.3.2/js/ionic.bundle.min.js"></script>
    </head>
    <body>
    
    <div class="bar bar-header">
      <div class="h1 title">提交注册信息</div>
    </div>
    <form action="{% url 'xxx01:index' %}" method="post">
{% csrf_token %}
    <div class="content has-header">
      <div class="list">
        <label class="item item-input">
          <input name='username' type="text" placeholder="用户名">
        </label>
        <label class="item item-input">
          <input name='email'  type="email" placeholder="email">
        </label>
        
        <label class="item item-input">
          <input name='pwd' type="password" placeholder="密码">
        </label>
       
        
      </div>
      <div class="padding">
        <button class="button button-block button-positive">添加</button>
      </div>
    </div>
    </from>
  </body>
</html>